### ISSUE TITLE
gmsh todo

### ISSUE THREAD

**Issue by jbrezmorf** [GeoMop/PyBS#7]
- [ ] gmsh_io: support for new GMSH format, parser simplification, element types support
- [ ] heal_mesh: stabilize
- [ ] occ_geom: complete geometry primitives, tutorial
- [ ] map_regions: tool to filter shapes and assign the regions
- [ ] mesh_deform: move selected nodes and smooth move in other nodes
